---
version: '1.0'
name: kafka_docker

networks: 
  kafka_net:
    name: kafka_net
    driver: bridge



services:

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - kafka_net
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:19092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  producer:
    image: kafka_producer
    container_name: kafka_producer
    depends_on: 
      - kafka
    networks: 
      - kafka_net
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: quickstart-producer.py
    environment:
      APP: quickstart-producer.py
      APP_TICK: 10
      KAFKA_SERVER: kafka
      KAFKA_PORT: 19092
      KAFKA_TOPIC: quickstart-events

  
  consumer:
    image: kafka_consumer
    container_name: kafka_consumer
    depends_on: 
      - kafka
    networks: 
      - kafka_net
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: quickstart-consumer.py
    environment:
      APP: quickstart-consumer.py
      KAFKA_SERVER: kafka
      KAFKA_PORT: 19092
      KAFKA_TOPIC: quickstart-events
        